volumes:
  pg18_primary_data: {}
  rabbitmq_data: {}
  valkey_data: {}

services:
  postgres-primary:
    image: postgres:18-alpine
    restart: "no"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PRIMARY_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    command: -c max_connections=100
    volumes:
      - pg18_primary_data:/var/lib/postgresql
      - ./deployment/local/postgres18:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    profiles:
      - postgres
      - infra
      - all

  valkey:
    image: valkey/valkey:alpine
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    command: valkey-server --save "" --appendonly no --protected-mode no --requirepass valkey
    profiles:
      - valkey
      - infra
      - all

  rabbitmq:
    image: rabbitmq:4-management-alpine
    restart: "no"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    profiles:
      - rabbitmq
      - infra
      - all
