spring:
  application:
    name: onboard-provider
  profiles:
    default: h2
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    primary:
      pool-name: onboard-writer-pool
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 30
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 300000
      leak-detection-threshold: 20000
      initialization-fail-timeout: 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
    replica:
      pool-name: onboard-reader-pool
      auto-commit: false
      read-only: true
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 300000
      leak-detection-threshold: 20000
      initialization-fail-timeout: 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    primary:
      jdbc-url: jdbc:postgresql://localhost:5432/onboard
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    replica:
      jdbc-url: jdbc:postgresql://localhost:5433/onboard
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
platform:
  database:
    type: postgres

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    primary:
      jdbc-url: jdbc:h2:mem:onboard;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
    replica:
      jdbc-url: jdbc:h2:mem:onboard;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
platform:
  database:
    type: h2
