[versions]
java = "21"
springBoot = "4.0.2"
springDependencyManagement = "1.1.7"
spotless = "8.2.1"
checkstyle = "13.1.0"
spotbugs = "4.9.8.2"
errorprone = "2.47.0"
archunit = "1.4.1"

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "springBoot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spotless-gradle-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }

[bundles]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs" }
errorprone = { id = "net.ltgt.errorprone", version = "errorprone" }
